### ISSUE TITLE
Why are NAS, ERI, VES and RIC different to the Badger PRO stats?

### ISSUE THREAD

**Issue by SimonStringerACT** [simonstringer/BadgerPicker#2]
I'm pretty sure that VES and RIC is somehow due to the teammate swap earlier in the year, but why are NAS and ERI different?

Need to understand why so that I can make sure my logic isn't wrong...

**Comment by simonstringer** [comment]
API=			BAD=	TOT=
NAS:	156		166		BAD+10 - MON
ERI:	162		167		BAD+5
VES:	213		217		BAD+4 - MON
RIC:	279		284		BAD+5

This seems to be down to the recording of the start position (grid) when a driver doesn't complete Quali.
At Monaco Badger has VES starting 21st (based on overtake points) but the API has him starting at grid 0. Same for NAS, start 22nd, grid 0.

VES got 9 bonus points at race 6 on badger, only 5 according to the calculation (grid = 0) This is his 4 point difference.
NAS got 15 bonus points at race 6 on badger, only 5 according to the calculation (grid = 0) This is his 10 point difference.
RIC and ERI miss out on the 5 points as their team mate started on grid 0.

Need to have a look into the quali API in cases where the grid is 0, hopefully that will have the data to help out!

**Comment by simonstringer** [comment]
Resolved the issue by using the qualifying URL to look up the qualifying position if the grid is set to 0. Needs a little tidying up, but the badger numbers now match.
